version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data:cached

  backend:
    build: .
    command: uvicorn todo.main:app --reload --port 8000 --host 0.0.0.0
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:8000
    links: 
      - postgres 
    depends_on:
      - postgres

volumes:
  db-data:
